#!/bin/bash

usage()
{
	echo "Usage: "
	echo "./runSuite suitefile.txt program"
}

if [ $# -lt 2 ] ; then #Check there is enough command line parameters.
	usage
	echo "Not enough parameters! (Needs two parameters!)" 1>&2
	exit 1
fi

if [ ! -e $1 ] ; then
	usage
	echo "$1 does not exist!" 1>&2
	exit 1
fi

if [ ! -e $2 ] ; then
	usage
	echo "$2 does not exist!" 1>&2
	exit 1
fi

parentdir="$(dirname "${1}")"

while read i
do #Check whether there is missing file
	if [ ! -r ${parentdir}/$i.in ] ; then
		echo "$i.in file is unreadable!" 1>&2
		exit 1
	fi
	if [ ! -r ${parentdir}/$i.out ] ; then
		echo "$i.out file is unreadable!" 1>&2
		exit 1
	fi
	if [ ! -e ${parentdir}/$i.out ] ; then
		echo "$i.out file does not exist!" 1>&2
		exit 1
	fi
	if [ ! -e ${parentdir}/$i.in ] ; then
		echo "$i.in file does not exist!" 1>&2
		exit 1
	fi
done < "$1"

while read i
do
	tempfoo=`basename $i`
	TMPFILE=`mktemp /tmp/${tempfoo}.XXXXXX` || exit 1
	./$2 < ${parentdir}/${i}.in > $TMPFILE
	diff $TMPFILE ${parentdir}/$i.out > /tmp/diff
	status=$?
	if [ $status == 1 ] ; then
   	echo "
Test failed: "File $i ""
	echo "Input:"
	cat $i.in
	echo "Expected:"
	cat $i.out
	echo "Actual:"
	cat $TMPFILE
	fi
	rm $TMPFILE
	rm /tmp/diff
done < "$1"
